name: Package Build and Release
on:
  push:
    tags:
      - '*.release'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Package
        run: |
           ./mvnw clean -Pnative native:compile
           ./props-demo.sh
      - name: Release and Upload
        uses: softprops/action-gh-release@v1
        with:
          files: './target/props'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}