name: Windows Tests

on: [workflow_dispatch]
      
jobs:
  push-and-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '17'
          components: 'native-image'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Testing
        run: |
           $SNAPSHOT_VERSION = & ./mvnw.cmd help:evaluate -Dexpression=project.version | Select-String -Pattern "^[^\[]*" | Select-String -Pattern Download -NotMatch | ForEach-Object { $_.Matches.Value }
           set RELEASE_VERSION=%SNAPSHOT_VERSION:-SNAPSHOT=%
           ./mvnw.cmd versions:set -DnewVersion=%RELEASE_VERSION%
           ./mvnw.cmd clean test
      
    